INSERT INTO stock VALUES (1, 'SOCKS', 3);
INSERT INTO stock VALUES (2, 'SHOES', 3);
INSERT INTO stock VALUES (3, 'T-SHIRT', 3);
INSERT INTO stock VALUES (4, 'JACKET', 3);
INSERT INTO stock VALUES (5, 'SNEAKERS', 1);
INSERT INTO stock VALUES (6, 'BALL', 3);
INSERT INTO stock VALUES (7, 'GLOVES', 3);
INSERT INTO stock VALUES (8, 'LEGGINGS', 3);
INSERT INTO stock VALUES (9, 'TOWEL', 3);
INSERT INTO stock VALUES (10, 'TOWEL B', 3);
INSERT INTO stock VALUES (11, 'SOCKS A', 3);
INSERT INTO stock VALUES (12, 'SOCKS B', 3);

EXIT;

